[theme]
base = "dark"
primaryColor = "#00ffa3"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1c222c"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
